version: "3"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html/ 
        networks:
            - default
        stdin_open: true
        tty: true
  
volumes:
    persistent: